### ISSUE TITLE
error running the tutorial1 with dump grid

### ISSUE THREAD

**Issue by bwd213** [nufeb/NUFEB#2]
Hello,
I was trying to run the first tutorial (biofilm growth)
I compiled the code with vtk following the instructions.

However, when running the tutorial with mpi, I got errors like below:
LAMMPS (20 Nov 2019)
Reading data file ...
  orthogonal box = (0 0 0) to (0.0001 4e-05 0.0001)
  12 by 4 by 1 MPI processor grid
  reading atoms ...
  41 atoms
  5 nutrients
40 atoms in group HET
1 atoms in group EPS
[cn31:62933] *** Process received signal ***
[cn31:62933] Signal: Segmentation fault (11)
[cn31:62933] Signal code: Address not mapped (1)
[cn31:62933] Failing at address: (nil)
[cn31:62950] *** Process received signal ***
[cn31:62988] *** Process received signal ***
[cn31:62988] Signal: Segmentation fault (11)
[cn31:62988] Signal code: Address not mapped (1)
[cn31:62988] Failing at address: (nil)

However, if I comment out "dump           du2 all grid 1000 grid_%_*.vti con" from the Inputscript-vtk.lammps, then it is able to run without errors.

I looked up this dump grid command in the manual, it mentions that each processor will write part of the file. Do you think it is something related with my openmpi? I am using openmpi-3.1.4
Do you have any suggestions?

Thanks.

**Comment by shelllbw** [comment]
Hi, zephyr213

I couldn't reproduce the error on Ubuntu-18.04 with openmpi-3.1.4. Could you let me know what is your Operating System? 
Will you get the error when using a single process to run (mpirun -np 1 ...) 
Also, if you comment out "dump grid" command, can you manage to run the simulation with "dump du1 all vtk" command, which generates atom_x_.vtu files

Bowen

**Comment by bwd213** [comment]
Hi Bowen,

Thank you for the fast reply. 

I changed to compiling using gnu7 and openmpi-1.10.7. And it worked without any issue.

To answer your question, I was using CentOS 7.7 with gnu8+openmpi-3.1.4. And mpirun -np 1 did not work. However, after commenting out "dump grid", the program was able to run and generated the atom_x_.vtu files.

And by the way, does NUFEB supports other MPI software, like intel mpi. I know lammps does, but not sure about the NUFEB packages.

And can I compile NUFEB packages with any lammps versions? Like the newer ones.

Thanks.
Norman

**Comment by valleymouth** [comment]
Hello,

The package should be MPI-agnostic. I have tested with intel mpi before and it worked, but it was some time ago. We have recently ported the NUFEB package to the most recent stable release of LAMMPS so it should work. We can help you if you find any problems compiling it.

**Comment by bwd213** [comment]
Thank you!
