### ISSUE TITLE
wall friction force

### ISSUE THREAD

**Issue by JohnRWF** [nufeb/NUFEB#21]
Dear developers,

Thanks for your excellent software. I'm studying about how surface friction force may influence biofilm expansion. I noticed in your software that the adhesive force between the wall and the microbes attached to the wall can be adjusted. However, this force alone cannot simulate the scenario where the biofilm expands (cells squeeze each other) and the wall's friction force hinders its expansion. So I wonder is it possible to adjust the wall's properties, such as friction force or friction coefficient?

**Comment by shelllbw** [comment]
You can either use lammps command: fix wall/gran command (https://docs.lammps.org/fix_wall_gran.html) to create a frictional wall, or create a layer of stationary particles which acts as wall to interact with biofilm particles, using
lattice, region, create_atoms (region), and fix_setforce commands.

**Comment by JohnRWF** [comment]
Sounds great! Thanks for your prompt reply.
