### ISSUE TITLE
example biofilm-het, unexplained behaviour for larger system

### ISSUE THREAD

**Issue by wmoebius** [nufeb/NUFEB#4]
Running the example biofilm-het (commit 1574b31403ff1423b99de00f414171d2ed64010d) with slightly modified parameters:

`Inputscript-vtk.lammps` (modified lines only):
```
variable EPSratio equal 1.2
fix k1 all kinetics 100 25 10 50 v_diffT v_layer niter 5000
run 500000
```

`atom.in` (modified line only):
```
0.000000e-04   2e-04  zlo zhi
```

I observe something like an soft 'barrier' at half system height. Part of the biofilm seems to grow beyond that point, part of it seems to be hinded by this 'barrier'. I do not have a biological explanation, which is why I am reporting this as an issue.

**Comment by shelllbw** [comment]
Hi Wolfram, the upper and bottom surfaces are bounded with frictional and adhesive walls. When changing domain height, you also need to change the height of these two walls with your new zhi in fix wall/gran hooke/history and fix walladh commands (the last two parameters).

Bowen

**Comment by wmoebius** [comment]
Thanks, I had not realised this. Could I request the feature to set system size at one place and propagate it to the other relevant parameters?

**Comment by wmoebius** [comment]
I can run a large system now. In Paraview, the colouring by type seems to break down for this larger system a while into the simulation. Is that something you are familiar with?

**Comment by shelllbw** [comment]
> Thanks, I had not realised this. Could I request the feature to set system size at one place and propagate it to the other relevant parameters?

They are actually LAMMPS commands. Allowing such flexibility would be useful in some systems where you want to define additional obstacle walls in the domain.

**Comment by shelllbw** [comment]
> I can run a large system now. In Paraview, the colouring by type seems to break down for this larger system a while into the simulation. Is that something you are familiar with?

Haven't met this issue before, are you using Glyph to represent particles (tutorial, visualisation part), also have a try with Point Gaussian.

**Comment by valleymouth** [comment]
Maybe a screenshot would help?

**Comment by wmoebius** [comment]
I believe this was an artifact when using Paraview. Closing now and reopening if it becomes a problem again.
