### ISSUE TITLE
Error when running "Tutorial: simulation of biofilm deformation and detachment"

### ISSUE THREAD

**Issue by wmoebius** [nufeb/NUFEB#5]
Installed OpenFoam 2.4.0 and built SediFoam (arguably) successfully.

The simulation aborts with `ERROR: Non-cubic Cartesian grid` (1574b31403ff1423b99de00f414171d2ed64010d). This is despite a cubic grid defined according to (default values):

`in.lammps`:
```
fix k1 all kinetics 100000 25 10 10 v_diffT v_layer niter 1
```

`atom.restart.in`:
```
   0.000000e-04   1.000000e-04  xlo xhi
   0.000000e-04   4.000000e-05  ylo yhi
   0.000000e-04   4.000000e-05  zlo zhi
```

**Comment by shelllbw** [comment]
Thanks for reporting this. Bug has fixed in the new commit.
